// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/dwsR.h"
#include <Rcpp.h>

using namespace Rcpp;

// openmp_self_test_cpp
Rcpp::List openmp_self_test_cpp();
RcppExport SEXP _dwsR_openmp_self_test_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(openmp_self_test_cpp());
    return rcpp_result_gen;
END_RCPP
}
// get_weight_fun_list_cpp
Rcpp::CharacterVector get_weight_fun_list_cpp();
RcppExport SEXP _dwsR_get_weight_fun_list_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_weight_fun_list_cpp());
    return rcpp_result_gen;
END_RCPP
}
// get_fun_list_cpp
Rcpp::CharacterVector get_fun_list_cpp();
RcppExport SEXP _dwsR_get_fun_list_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_fun_list_cpp());
    return rcpp_result_gen;
END_RCPP
}
// p_focal_cpp
std::vector<double> p_focal_cpp(Rcpp::NumericMatrix data, std::vector<double> kernel, size_t k_rows, size_t k_cols, size_t k_lays, int transform_fun, int reduce_fun);
RcppExport SEXP _dwsR_p_focal_cpp(SEXP dataSEXP, SEXP kernelSEXP, SEXP k_rowsSEXP, SEXP k_colsSEXP, SEXP k_laysSEXP, SEXP transform_funSEXP, SEXP reduce_funSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< size_t >::type k_rows(k_rowsSEXP);
    Rcpp::traits::input_parameter< size_t >::type k_cols(k_colsSEXP);
    Rcpp::traits::input_parameter< size_t >::type k_lays(k_laysSEXP);
    Rcpp::traits::input_parameter< int >::type transform_fun(transform_funSEXP);
    Rcpp::traits::input_parameter< int >::type reduce_fun(reduce_funSEXP);
    rcpp_result_gen = Rcpp::wrap(p_focal_cpp(data, kernel, k_rows, k_cols, k_lays, transform_fun, reduce_fun));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dwsR_openmp_self_test_cpp", (DL_FUNC) &_dwsR_openmp_self_test_cpp, 0},
    {"_dwsR_get_weight_fun_list_cpp", (DL_FUNC) &_dwsR_get_weight_fun_list_cpp, 0},
    {"_dwsR_get_fun_list_cpp", (DL_FUNC) &_dwsR_get_fun_list_cpp, 0},
    {"_dwsR_p_focal_cpp", (DL_FUNC) &_dwsR_p_focal_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_dwsR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
