# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.openmp_self_test_cpp <- function() {
    .Call(`_dwsR_openmp_self_test_cpp`)
}

.get_weight_fun_list_cpp <- function() {
    .Call(`_dwsR_get_weight_fun_list_cpp`)
}

.get_fun_list_cpp <- function() {
    .Call(`_dwsR_get_fun_list_cpp`)
}

.p_focal_cpp <- function(data, kernel, k_rows, k_cols, k_lays, transform_fun, reduce_fun, default_value) {
    .Call(`_dwsR_p_focal_cpp`, data, kernel, k_rows, k_cols, k_lays, transform_fun, reduce_fun, default_value)
}

